[project]
name = 'chainquest'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.sip009-nft-trait]
path = 'contracts/sip009-nft-trait.clar'
clarity_version = 3
epoch = 'latest'

[contracts.achievement-badges]
path = 'contracts/achievement-badges.clar'
clarity_version = 3
epoch = 'latest'

[contracts.leaderboard]
path = 'contracts/leaderboard.clar'
clarity_version = 3
epoch = 'latest'

[contracts.quest-manager]
path = 'contracts/quest-manager.clar'
clarity_version = 3
epoch = 'latest'

[contracts.reward-distributor]
path = 'contracts/reward-distributor.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
